project:
  type: website
  resources:
    - CNAME

website:
  title: "Langmead Lab @ JHU"
  favicon: images/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - people.qmd
      - teaching.qmd
      - contact.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
