---
title: "People"
---

## Current members

| Name/Role                                         | Links                                                                                                                                                                                                                                                                   |
|---------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Ben Langmead** <br /> Principal Investigator    | [GitHub](https://github.com/BenLangmead),    [Scholar](https://scholar.google.com/citations?user=2JMaTKsAAAAJ&hl=en), [Talks](https://speakerdeck.com/benlangmead/), [BlueSky](https://bsky.app/profile/benlangmead.bsky.social), [LinkedIn](https://www.linkedin.com/in/benjaminlangmead/) |
| **Rone Charles** <br /> Software Engineer         | [GitHub](https://github.com/ch4rr0)                                                                                                                                                                                                                                     |
| **Mohsen Zakeri** <br /> Postdoctoral Fellow      | [GitHub](https://github.com/mohsenzakeri/),  [Scholar](https://scholar.google.com/citations?user=7I-mNqcAAAAJ&hl=en&oi=ao), [Twitter](https://twitter.com/MohsenZakeri1), [LinkedIn](https://www.linkedin.com/in/mohsen-zakeri-56017576/)                                |
| **Sina Majidian** <br /> Postdoctoral Fellow      | [GitHub](https://github.com/sinamajidian/),  [Scholar](https://scholar.google.com/citations?user=pgzi_1QAAAAJ&hl=en&oi=ao),                                               [LinkedIn](https://www.linkedin.com/in/sina-majidian/)                                |
| **Jessica Bonnie** <br /> Ph.D. Student           | [GitHub](https://github.com/jessicabonnie/), [Scholar](https://scholar.google.com/citations?user=mTTrb6MAAAAJ&hl=en&oi=ao), [LinkedIn](https://www.linkedin.com/in/jessicabonnie/)                                                                                      |
| **Naga Sai Kavya Vaddadi** <br /> Ph.D. Student   | [GitHub](https://github.com/kvaddad1),       [Scholar](https://scholar.google.com/citations?user=gcUPxzwAAAAJ&hl=en&oi=ao)                                                                                                                                                    |
| **Mao-Jan Lin** <br /> Ph.D. Student              | [GitHub](https://github.com/maojanlin),      [Scholar](https://scholar.google.com/citations?user=L_EVYB8AAAAJ&hl=en&oi=ao), [Twitter](https://twitter.com/MaoJanLin)                                                                                                         |
| **Vikram Shivakumar** <br /> Ph.D. Student        | [GitHub](https://github.com/vikshiv),        [Scholar](https://scholar.google.com/citations?user=LiuMoYgAAAAJ&hl=en),       [BlueSky](https://bsky.app/profile/vikramshivakumar.bsky.social)                                                                                 |
| **Stephen Hwang** <br /> Ph.D. Student            | [GitHub](https://github.com/StephenHwang),   [LinkedIn](https://www.linkedin.com/in/hwangjstephen/)                                                                                                                                                                       |
| **Nathaniel Brown** <br /> Ph.D. Student          | [GitHub](https://github.com/drnatebrown),    [LinkedIn](https://www.linkedin.com/in/nathaniel-brown-60b654171/)                                                                                                                                                            |

## Alumni

| Name/Training                                                                                                            | Currently                                                     |
|-----------------------|------------------------------------------------|
| **Omar Ahmed** <br /> Ph.D. | Postdoctoral Scientist <br /> New York Genome Center |
| **Anna Liebhoff** <br /> Postdoctoral Fellow <br /> co-mentored with [Ben Larman](https://labs.pathology.jhu.edu/larman/) | Scientist & Entrepreneur |
| **Nae-Chyun Chen** <br /> Ph.D. | Senior Software Engineer, Comp. Genomics <br /> Exai Bio |
| **Taher Mun** <br /> Ph.D.      | Principal Bioinformatics Software Engineer <br /> Roche  |
| **Daniel Baker** <br /> Ph.D.   | Software Engineer <br /> Roche              |
| **Dominik Kempa** <br /> Postdoctoral Fellow                                                                             | Assistant Professor, CS <br /> Stony Brook University         |
| **Jonathan Ling** <br /> Postdoctoral (Kavli) Fellow <br /> co-mentored with [Seth Blackshaw](https://blackshawlab.com/) | Assistant Professor, Pathology <br /> Johns Hopkins Medicine  |
| **Christopher Wilks** <br /> Ph.D.                                                                                       | Computational Scientist <br /> Neumora                        |
| **Charlotte Darby** <br /> Ph.D. <br /> co-mentored with [Mike Schatz](https://schatz-lab.org/)                          | Computational Biologist <br /> Takeda Pharmaceuticals         |
| **Brad Solomon** <br /> Postdoctoral Fellow                                                                              | Teaching Assistant Professor <br /> UIUC CS                   |
| **Jacob Pritt** <br /> Ph.D.                                                                                             | Lead Computational Scientist <br /> Mimetics            |
| **Abhinav Nellore** <br /> Postdoctoral Fellow                                                                           | Formerly: Assistant Professor <br /> Oregon Health & Science University |
| **Derrick Wood** <br /> Postdoctoral Fellow                                                                              | [Founder and Freelancer](https://www.linkedin.com/in/derrick-wood-phd/)                |