---
title: "Research"
---

## Papers

For a complete and up-to-date publication list, so the [Google Scholar](https://scholar.google.com/citations?user=2JMaTKsAAAAJ&hl=en) profile.

## Software

### Alignment

* [Bowtie] -- fast short read alignment
* [Bowtie 2]  -- fast gapped read alignment for short reads
* [Qtip] -- mapping quality predictions
* [Samovar] -- somatic mosaic variant detection
* [Vargas] -- heuristic-free read alignment
* [Arioc] by Richard Wilton -- fast GPU-based alignment
* [HISAT] by Daehwan Kim -- fast spliced alignment

### Pangenome Indexing and Alignment

* [FORGe] -- selecting variation to include in a pangenome
* [Reference Flow] -- multi-genome alignment
* [r-index] -- by Nicola Prezza with modifications by Taher Mun, pangenome index
* [MONI] -- by Max Rossi, fast MEM finding with a pangenome index
* [SPUMONI] -- fast classification with a pangenome index
* [rowbowt] -- efficient pangenome genotyping
* [LevioSAM] -- lift-over for pangenome alignment
* [LevioSAM 2] -- pangenome alignment across structurally distinct assemblies

### Genomic Sketching

* [Dashing] -- genomic sketching with HyperLogLog
* [Dashing 2] -- genomic sketching with SetSketch
* [DandD] -- k-independent measurement of sequence content & similarity

### Large-scale Reanalysis

* [recount3] -- vast compendium of analyzed, summarized RNA-seq experiments
* [Snaptron] -- queryable index over recount
* [ASCOT] by Jonathan Ling -- catalog of cell type specific splicing
* [FC-R2] by Eddie Imada & Diego Fernando Sanchez -- recount data analyzed with FANTOM annotations
* [REPAC] by Eddie Imada -- catalog of alternate polyadenylation
* (superseded) [Rail-dbGaP]
* (superseded) [recount2]
* (superseded) [recount]
* (superseded) [Intropolis]
* (superseded) [Myrna]
* (superseded) [Crossbow]

### RNA-seq analysis

* [Monorail] -- reproducible recount3 analysis pipeline
* [Megadepth] -- RNA-seq coverage analysis
* [Polyester] by Alyssa Frazee -- RNA-seq read simulator
* [Boiler] -- compression of RNA-seq alignments
* (superseded) [Rail-RNA]

### Other

* [Samovar] -- somatic mosaic variant detection
* [Lighter] by Li Song -- short read error correction
* [minicore] -- fast k-means clustering
* [Bsmooth] -- bisulfity sequencing data analysis

{{< include _links.qmd >}}
